version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run: npm install
      - run: npm run build
      - run:
          name: Run Tests
          command: bundle exec rspec
